### List all Messages
GET http://localhost:3001/messages

### Create a Message
POST http://localhost:3001/messages
content-type: application/json

{
  "id": 1,
  "message": "The World is reabilitating"
}

### Get a Message
GET http://localhost:3001/messages/23r2r